version: '3'
services:

    web:
        image: nginx:latest
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        volumes:
            - ../raiz:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        networks:
            - app-network

    php:
        build:
            context: ./phpDockerFile
            dockerfile: Dockerfile
        container_name: php-fpm
        volumes:
            - ../raiz:/www
        networks:
            - app-network


    db:
        image: postgres
        container_name: postgres
        restart: always
        tty: true
        environment:
            POSTGRES_PASSWORD: "gustavo01"
        ports:
            - "15432:5432"
        networks:
            - app-network
        
    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "gustavo.torregrosa@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: "gustavo01"
        ports:
            - "16543:80"
        depends_on:
            - db
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
